package bg.softuni.mmusic.model.enums;

public enum StyleType {
    POP, DANCE_POP, POP_RAP, HIP_HOPE,
    ROCK, MODERN_ROCK, MELLOW_GOLD, SOFT_ROCK, CLASSIC_ROCK,
    HIPHOP, MELODIC_RAP, TRAP, QUEENS_HIP_HOP,
    LATIN, TRAP_LATINO, LATIN_POP, TROPICAL, LATIN_ROCK,
    COUNTRY, NEW_AMERICANA, COUNTRY_POP, AUSTRALIAN_COUNTRY,
    FOLK, INDIE_FOLK, ROOTS_ROCK, ANTI_FOLK,
    CLASSICAL, CLASSICAL_PIANO, VIOLIN, OPERA,
    JAZZ, JAZZ_FUSION, COOL_JAZZ, JAZZ_FUNK,
    METAL
}
